name: Package Release
on: [create]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Zip dist
        run: cd module && zip -r ../reverse-initiative-order.zip *

      - name: Create Release
        id: create_versioned_release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          name: ${{ github.ref }}
          draft: true
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "./module/module.json,./reverse-initiative-order.zip"
          tag: ${{ github.ref }}
